version: '3.9'
services:
  db:
    container_name: scuole_db
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
        POSTGRES_USERNAME: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres


  pg-admin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:5050"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050



